// 插件 / Skills / MCP 的内置中文说明。
// 列表里那一行小字优先级:用户自己写的备注 > 这张表 > SKILL.md / plugin.json 里的英文 description。
// 表按"列表里显示的名字"取键:用户级 skill 是裸名,插件自带的是 `插件名:skill名`,MCP 是 server 名。
export const EXT_NOTE_ZH: Record<string, string> = {
  // ---- 插件 ----
  "andrej-karpathy-skills": "Karpathy 批的写码四毛病变成规矩:先澄清假设、不过度抽象、只改该改的",
  "claude-hud": "状态栏实时 HUD,显示上下文占用、当前工具、子代理和 todo 进度",
  "ponytail": "每轮注入「最懒资深工程师」规则,按 YAGNI 和标准库阶梯逼你少写代码",
  "caveman": "用 hook 把回答压成穴居人短句,省约 65% 输出 token,代码和报错原样不动",
  "rust-analyzer-lsp": "官方插件,接 rust-analyzer,给 .rs 提供跳转定义、找引用和诊断",
  "superpowers": "obra 的技能库兼方法论:先逼出规格与计划,再用子代理按 TDD 逐任务实现复审",

  // ---- MCP ----
  "pencil": "读写加密 .pen 设计文件:改画布节点、变量、布局,截图与导出",
  "chrome-devtools": "用 CDP 驱动真实 Chrome:点击填表、看控制台与网络、截图、跑性能 trace",
  "company-meter": "Atisbo 计量接入:扫出模型调用点,设计事件埋点与成本价、套餐订阅计费",
  "claude_ai_Gmail": "搜邮件线程、读正文、建改草稿、管标签;只能写草稿不直接发信",
  "claude_ai_Google_Calendar": "查建改日程、回复邀请、列日历、按参与者空档推荐会议时间",
  "claude_ai_Google_Drive": "搜云端文件、读取下载内容、新建复制文件、查元数据与共享权限",
  "claude_ai_Zoom_for_Claude": "检索 Zoom 会议录制、转录和 AI 摘要,读写 Zoom Docs 笔记",
  "claude_ai_monday_com": "读写看板分组条目和文档,建仪表盘、表单、自动化,可直连 GraphQL",
  "claude_ai_Fellow_ai": "把 Fellow 录的会议转录、摘要、决议和待办拉进来供检索问答",
  // claude.ai 云端连接器在列表里按 "claude.ai Xxx" 显示(会话上报的原名),两种写法都留着
  "claude.ai Gmail": "搜邮件线程、读正文、建改草稿、管标签;只能写草稿不直接发信",
  "claude.ai Google Calendar": "查建改日程、回复邀请、列日历、按参与者空档推荐会议时间",
  "claude.ai Google Drive": "搜云端文件、读取下载内容、新建复制文件、查元数据与共享权限",
  "claude.ai Zoom for Claude": "检索 Zoom 会议录制、转录和 AI 摘要,读写 Zoom Docs 笔记",
  "claude.ai monday.com": "读写看板分组条目和文档,建仪表盘、表单、自动化,可直连 GraphQL",
  "claude.ai Fellow.ai": "把 Fellow 录的会议转录、摘要、决议和待办拉进来供检索问答",

  // ---- 用户级 Skills ----
  "animation-vocabulary": "把「弹出来那个感觉」这类模糊描述反查成动效术语,如 Pop in、橡皮筋滚动",
  "apple-design": "把苹果的手势、弹簧动效、材质与排版规范翻译成 Web 做法",
  "authkit-design": "AuthKit 设计系统,只在明确说「AuthKit 风格」时才启用",
  "banner-design": "做社媒、广告、官网 hero 和印刷 banner,多套艺术方向配 AI 生成图",
  "brand": "品牌语调、视觉识别、信息框架与素材一致性检查",
  "brandkit": "生成高端品牌规范板、logo 体系、识别提案的图像技能",
  "brutalist-skill": "粗野派界面:瑞士排印加军用终端感,硬网格、极端字号对比、做旧噪点",
  "chat-code-design": "chat-code 自家设计系统,只在明确说「chat-code 风格」时才启用",
  "design": "设计全家桶:品牌识别、design token、logo、CI 手册、演示页、banner、图标",
  "design-system": "三层 token 架构(原子→语义→组件)、组件规格与品牌一致的幻灯片生成",
  "diagnosing-bugs": "难 bug 和性能回归的诊断循环,说「排查一下」「debug」时用",
  "emil-design-eng": "Emil Kowalski 那套 UI 打磨观:组件设计、动效取舍和看不见的细节",
  "find-animation-opportunities": "只读扫代码,找出该动却没动的地方并给出具体数值,不动手改",
  "gpt-tasteskill": "GSAP 动效与编辑感排版的高强度落地页规范,含 ScrollTrigger 钉滚叠",
  "grill-with-docs": "用连环追问把方案问透,过程中顺手产出 ADR 和术语表",
  "hue": "元技能:根据一句话或一张截图生成一套新的设计语言 skill",
  "image-to-code-skill": "先自己生成设计稿再逐段还原成网页代码,偏大图分段实现",
  "imagegen-frontend-mobile": "生成 iOS / Android 原生质感的 App 界面概念图与多屏流程",
  "imagegen-frontend-web": "生成网站设计参考图,一屏一段单独出图,禁止把多段压成一张",
  "improve-animations": "以资深动效顾问视角审全仓动效,产出优先级清单和可交付的改造计划",
  "ljg-roundtable": "圆桌辩论框架:主持人请代表人物多视角交锋,说「圆桌讨论」时触发",
  "minimalist-skill": "极简编辑风界面:暖调单色、排版对比、扁平 bento,无渐变无重阴影",
  "output-skill": "禁止偷懒截断和占位符,强制输出完整代码,超长自动干净分段",
  "redesign-skill": "给现有网站做体检并升级到高端观感,不破坏原有功能和框架",
  "review-animations": "按 Emil 那套标准审动效代码,默认挑刺,通过要靠说服",
  "slides": "做带 Chart.js、design token 和文案公式的策略型 HTML 演示",
  "soft-skill": "教 AI 按高端工作室的字体、间距、阴影和卡片结构做出「贵」的观感",
  "stitch-skill": "给 Google Stitch 生成 DESIGN.md,约束排版、配色、非对称布局与微动效",
  "taste-skill": "反模板前端:读需求自己定设计方向,改版先审计再动手",
  "taste-skill-v1": "taste-skill 的旧 v1 版,只为兼容依赖它原行为的老项目保留",
  "tdd": "测试先行:红-绿-重构,想先写测试再做功能或修 bug 时用",
  "to-prd": "把当前对话直接整理成 PRD 并发到项目 issue 跟踪器,不再追问",
  "ui-styling": "用 shadcn/ui + Tailwind 做可访问的界面组件和响应式布局",
  "ui-ux-pro-max": "本地可搜的 UI/UX 库:50+ 风格、161 配色、57 字体对、99 条 UX 准则",
  "volume-price-analysis": "量价关系框架:量=分歧、位=灵魂、效率=真伪,用于个股复盘与异动归因",

  // ---- 插件自带 Skills ----
  "caveman:caveman": "开启穴居人压缩输出模式,分 lite / full / ultra 档",
  "caveman:cavecrew": "决定何时派 caveman 子代理:定位代码、小改、审 diff 各一个",
  "caveman:caveman-commit": "生成压缩版 commit message,Conventional Commits,标题不超 50 字符",
  "caveman:caveman-compress": "把 CLAUDE.md、todo 这类记忆文件压成穴居人格式省输入 token",
  "caveman:caveman-help": "caveman 全部模式与命令的速查卡",
  "caveman:caveman-review": "压缩版代码评审:一条一行,位置 + 问题 + 修法",
  "caveman:caveman-stats": "读会话日志算本次真实 token 用量与省下的量",
  "ponytail:ponytail": "最懒但能跑的方案:先问要不要做,再标准库、原生能力、一行搞定",
  "ponytail:ponytail-audit": "全仓过度设计体检,列出该删、该简化、该换成标准库的地方",
  "ponytail:ponytail-debt": "收集代码里的 ponytail: 注释,汇成技术债台账,防止「以后再说」烂掉",
  "ponytail:ponytail-gain": "用基准中位数展示 ponytail 省下的代码量、成本和时间",
  "ponytail:ponytail-help": "ponytail 全部模式与命令的速查卡",
  "ponytail:ponytail-review": "只针对过度设计的评审:找出可删的重复造轮子和空抽象",
  "karpathy:karpathy-guidelines": "减少 LLM 写码通病:别过度复杂、只做最小改动、把假设和验收讲清楚",
  "claude-hud:setup": "一键装好 claude-hud 状态栏并写进 settings.json",
  "claude-hud:configure": "调 claude-hud 状态栏显示哪些字段和样式",
  "superpowers:brainstorming": "用提问把模糊想法逼成一份可实现的规格",
  "superpowers:writing-plans": "把规格拆成子代理能照做的实现计划",
  "superpowers:executing-plans": "按计划逐条执行并核对完成标准",
  "superpowers:subagent-driven-development": "一个任务一个子代理,主线程只做调度和验收",
  "superpowers:dispatching-parallel-agents": "并行派多个子代理的分工与合流套路",
  "superpowers:test-driven-development": "红-绿-重构,测试先行的落地流程",
  "superpowers:systematic-debugging": "系统化排障:先复现,再二分定位,最后验证根因",
  "superpowers:requesting-code-review": "把改动整理成可评审的包并请子代理评审",
  "superpowers:receiving-code-review": "接住评审意见并逐条处理或反驳",
  "superpowers:verification-before-completion": "收工前跑一遍端到端验证,不靠「应该没问题」",
  "superpowers:using-git-worktrees": "用 git worktree 让并行改动互不打架",
  "superpowers:finishing-a-development-branch": "分支收尾:合并、清理 worktree 和残留",
  "superpowers:writing-skills": "写新 skill 的规范:何时触发、怎么组织 SKILL.md",
  "superpowers:using-superpowers": "superpowers 技能体系的入口和用法索引",
};
